### ISSUE TITLE
JEI not showing recipes

### ISSUE THREAD

**Issue by Golden-Hall** [Golden-Hall/Agora-Interregnum#7]
**Modpack version:**
eg. 0.6.3-Beta

**Describe the bug**
JEI not showing recipes for anything

**To Reproduce**
Join world, open inventory, try to view recipe of any item

**Expected behavior**
Recipe should display

**Screenshots**
N/A

**Additional context**
N/A

**Comment by incbase** [comment]
The same bug, almost all crafting recipes are locked except trading with MineColonies villagers.

**Comment by Golden-Hall** [comment]
> The same bug, almost all crafting recipes are locked except trading with MineColonies villagers.

Currently working on this, will hopefully be fixed for the next update

**Comment by Necessitysslave** [comment]
Found it! (took a fair number of hours)
config\openloader\data\agora_interregnum_recipes\data\ars_omega\recipes\proactive_1.json

Really not too sure what the issue is. If I change the file contents to be the same as proactive_2.json then JEI works. If I change the Level to 1 or remove the level from that file JEI doesn't work

I've deleted the file currently
